name = "gaussian_process"
version = "0.1.0"
exports = [
    "rbf_cov",
    "matern12_cov",
    "matern32_cov",
    "matern52_cov",
    "rational_quad_cov",
    "periodic_cov",
    "local_periodic_cov",
    "damped_periodic_cov",
    "rq_periodic_cov",
    "spectral_mixture_cov",
    "cosine_cov",
    "linear_cov",
    "polynomial_cov",
    "arccosine_cov",
    "wiener_cov",
    "brownian_bridge_cov",
    "ornstein_uhlenbeck_cov",
    "integrated_ornstein_uhlenbeck_cov",
    "white_cov",
    "constant_cov",
    "latent",
    "predict_marginal_mean",
    "group_sizes",
    "rbf_cross_cov",
    "matern12_cross_cov",
    "matern32_cross_cov",
    "matern52_cross_cov",
    "rational_quad_cross_cov",
    "periodic_cross_cov",
    "local_periodic_cross_cov",
    "damped_periodic_cross_cov",
    "rq_periodic_cross_cov",
    "spectral_mixture_cross_cov",
    "cosine_cross_cov",
    "linear_cross_cov",
    "polynomial_cross_cov",
    "arccosine_cross_cov",
    "wiener_cross_cov",
    "brownian_bridge_cross_cov",
    "ornstein_uhlenbeck_cross_cov",
    "integrated_ornstein_uhlenbeck_cross_cov",
    "white_cross_cov",
    "constant_cross_cov",
    "marginal_normal_lpdf",
    "predict_marginal_rng",
    "predict_latent_rng",
    "group_starts",
    "group_rows",
]
